<div class="login">
    <h1>Login</h1>
    <form action=".<?= htmlentities($this->request->server->REQUEST_URI, ENT_QUOTES); ?>" method="post">
        <input type="text" name="username" placeholder="Username" id="username" required>
        <input type="password" name="password" placeholder="Password" id="password" required>
        <input type="submit" value="Login">
    </form>
    <span id='loginMessage'><?= $message ?></span>
</div>