<? if (count($transactions) > 0): ?>
<div class="table">
    <div class="tr">
        <div class="td">Date</div>
        <div class="td">Order</div>
        <div class="td">Transaction</div>
        <div class="td">Description</div>
        <div class="td">Type</div>
        <div class="td">Symbol</div>
        <div class="td">Instruction</div>
        <div class="td">Amount</div>
        <div class="td">Price</div>
        <div class="td">Fees</div>
        <div class="td">Cost</div>
        <div class="td">Outstanding</div>
    </div>

    <? foreach ($transactions as $transaction): ?>
    <? if ($transaction->error == 'true'): ?>
    <div class="tr error">
    <? else: ?>
    <div class="tr">
    <? endif ?>
        <div class="td"><?= $transaction->transactionDate ?></div>
        <div class="td"><?= $transaction->orderId ?></div>
        <div class="td"><?= $transaction->transactionId ?></div>
        <div class="td"><?= $transaction->description ?></div>
        <div class="td"><?= $transaction->transactionSubType ?></div>
        <div class="td"><?= $transaction->symbol ?></div>
        <div class="td"><?= $transaction->instruction ?></div>
        <div class="td"><?= number_format($transaction->amount, 0, '.', ',') ?></div>
        <div class="td"><?= number_format($transaction->price, 2, '.', ',') ?></div>
        <div class="td"><?= number_format($transaction->secFee, 2, '.', ',') ?></div>
        <div class="td"><?= number_format($transaction->netAmount, 2, '.', ',') ?></div>
        <div class="td"><?= number_format($transaction->outstanding, 0, '.', ',') ?></div>
    </div>
    <? endforeach ?>

    <div class="tr">
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td">-</div>
        <div class="td"><?= $transaction->outstanding ?></div>
    </div>
</div>
<? else: ?>
<h3> No transactions yet</h3>
<? endif ?>