<div id="navwrapper">
    <div id="nav" class="content">
        <a class="nav-item" href="./home">Home</a>
        <a class="nav-item" href="./transactions">Transactions</a>
        <a class="nav-item" href="./trades">Trades</a>
        <a class="nav-item" href="./summary">Summary</a>
        <a class="nav-item" href="./account">Account</a>
        <a class="nav-item" href="./logout">Logout</a>
    </div>
</div>